### ISSUE TITLE
edit readme to provide notes on installation

### ISSUE THREAD

**Issue by someparsa** [ClearCalcs/pyCUFSM#15]
Hi and Thank you indeed for such amazing package.

Could you provide some clear notes in read me so that the users can read them and install the package? It seems that we should download the package and address local root in the codes but this sometimes does not work, at least I did not succeed to do so. One option may be distributing your package by PIP PyPI so that users can easily install them using their command.

**Comment by someparsa** [comment]
By the way, I created a pull request on readme file to add some lines about installation from git. Some users may not be professional enough to know how packages may be installed directly from github.

**Comment by smith120bh** [comment]
I've just published the first public release of pyCUFSM, using the PyPI distribution system. I've updated the readme to reflect this, but you can now install pycufsm (along with some various optional dependencies, such as Jupyter Notebooks requirements) using `pip install pycufsm`! 

I believe this solves this issue, and so I'm closing this!
