### ISSUE TITLE
Issue in results for bending

### ISSUE THREAD

**Issue by someparsa** [ClearCalcs/pyCUFSM#84]
I wonder do the results from this package are verified / compared with the outputs of the MATLAB version of the cufsm? Results for compression on my analysis are close to existing ones but for bending, they are far away.

**Comment by smith120bh** [comment]
Hi @someparsa ,

Thanks for checking! Yes, there is an automated test suite that is based upon the original validations that Ben Schafer published when he first created the MATLAB version of CUFSM (and which were published in the [AISI DSM Design Guide 2006](https://github.com/ClearCalcs/pyCUFSM/files/12734477/AISI.DSM.guide.jan.2006.FINAL.pdf). The tests literally load the original .mat file into Python and check that we're coming up with the same (or very close to the same) results. You can see those tests under the `/tests` directory in this repository, and the associated `mat_files` subdirectory. 

That said, I've only added about a third of the original validation tests, and those validation tests do not cover every possible scenario! If you've found a mismatch, then please add some more details to your ticket here, as I want to fix that ASAP! Unfortunately, I don't have enough information to do anything based upon your initial comment here, though.

**Comment by smith120bh** [comment]
Closing due to not enough information to address.
